longevity/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
from rest_framework.urlpatterns import format_suffix_patterns
from welltory import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('welltory/passwordreset/', auth_views.PasswordResetView.as_view(template_name='clinic/password_reset.html'),
          name='password_reset'),
    path('welltory/passwordreset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='clinic/password_reset_done.html'),
         name='password_reset_done'),
    path('welltory/passwordresetconfirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='clinic/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('welltory/passwordresetcomplete/', auth_views.PasswordResetCompleteView.as_view(
         template_name='clinic/password_reset_complete.html'), name='password_reset_complete'),
    path('welltory/', include('welltory.urls')),
    path('welltory/biomarker', views.BioMarkerList.as_view()),
    path('welltory/parameter', views.ParameterList.as_view()),
    path('welltory/reading', views.ReadingList.as_view()),
    path('welltory/disease', views.DiseaseList.as_view()),
    path('welltory/recommendation', views.RecommendationList.as_view())
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

welltory/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'welltory'
urlpatterns = [
   path('register/', views.UserRegisterView.as_view(success_url='../'), name='register'),
   path('', auth_views.LoginView.as_view(template_name='clinic/index.html'), name='index'),
   path('logout/', auth_views.LogoutView.as_view(template_name='clinic/logout.html'), name='logout'),
   path('home', views.home, name='home'),
   path('profile/', views.ProfileView.as_view(), name='profile'),
   path('updateuser/', views.updateuser, name='updateuser'),
   path('updatepractitioner/', views.updatepractitioner, name='updatepractitioner'),
   path('patientlist/', views.PatientListView.as_view(), name='patientlist'),
   path('patientdetails/<int:pk>', views.PatientDetailView.as_view(), name='patientdetails'),
   path('createpatient/', views.PatientCreateView.as_view(), name='createpatient'),
   path('updatepatient/<int:pk>/update', views.PatientUpdateView.as_view(), name='updatepatient'),
   path('deletepatient/<int:pk>/delete', views.PatientDeleteView.as_view(), name='deletepatient'),
   path('diagnosislist/<national_id>', views.DiagnosisListView.as_view(), name='diagnosislist'),
   path('diagnosisdetails/<int:pk>', views.DiagnosisDetailView.as_view(), name='diagnosisdetails'),
   path('creatediagnosis/<national_id>', views.diagnosiscreate, name='creatediagnosis'),
   path('diagnosisuploadprep/<national_id>', views.diagnosisuploadprep, name='diagnosisuploadprep'),
   path('diagnosisupload', views.diagnosisupload, name='diagnosisupload'),
   path('diagnosisdoclist/<id>/', views.DiagnosisDocListView.as_view(), name='diagnosisdoclist'),
   path('diagnosisdownload/<id>/', views.diagnosisdownload, name='diagnosisdownload'),
   path('documenttext/<int:pk>', views.ConvertedTextDetailView.as_view(), name='documenttext'),
]

welltory/forms.py
from django import forms
from django.forms import ModelForm, Textarea
from django.forms.widgets import DateInput
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Practitioner, Patient, Diagnosis


# USERS, PRACTITIONERS & AUTHENTICATION ====================================================================================
# ======================================================================================================================
class UserRegisterForm(UserCreationForm):
    first_name = forms.CharField(max_length=40, required=True)
    last_name = forms.CharField(max_length=40, required=True)
    email = forms.EmailField(max_length=80, required=True)
    password1 = forms.CharField(
        label='Password',
        strip=False,
        widget=forms.PasswordInput,)

    password2 = forms.CharField(
        label='Repeat Password',
        widget=forms.PasswordInput,
        strip=False,)

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email',)
        help_texts = {
            'username': None,
        }


class UserUpdateForm(forms.ModelForm):
    first_name = forms.CharField(max_length=40, required=True)
    last_name = forms.CharField(max_length=40, required=True)
    email = forms.EmailField(max_length=80, required=True)

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')
        help_texts = {
            'username': None,
        }


# form to create/update lawyer details
class PractitionerUpdateForm(forms.ModelForm):
    class Meta:
        model = Practitioner
        fields = ('dateOfBirth',
                  'gender',
                  'national_id',
                  'mobile',
                  'street1',
                  'street2',
                  'city',
                  'country',
                  'image')

        labels = {
            'dateOfBirth': 'Date Of Birth',
            'gender': 'Gender',
            'national_id': 'National ID',
            'mobile': 'Mobile',
            'street1': 'Address (Street)',
            'street2': 'Address (Surburb)',
            'city': 'City',
            'country': 'Country'
        }

        widgets = {'dateOfBirth': DateInput(attrs={'type': 'date'})}


class PatientForm(forms.ModelForm):
    class Meta:
        model = Patient
        fields = (
            'first_name',
            'last_name',
            'mobile',
            'email',
            'street1',
            'street2',
            'city',
            'country',
            'dateOfBirth',
            'national_id',
            'gender',
        )

        labels = {
            'first_name': 'First Name',
            'last_name': 'Last Name',
            'mobile': 'Mobile',
            'email': 'Email Address',
            'address1': 'Address (Street)',
            'address2': 'Address (Surburb)',
            'city': 'City',
            'country': 'Country',
            'dateOfBirth': 'Date of Birth',
            'national_id': 'National ID',
            'gender': 'Gender',
        }

        widgets = {'dateOfBirth': DateInput(attrs={'type': 'date'})}


# form for disabled field inputs on user profile
class ProfileGrayedForm(forms.ModelForm):
    first_name = forms.CharField(max_length=40, disabled=True)
    last_name = forms.CharField(max_length=40, disabled=True)
    email = forms.EmailField(max_length=80, disabled=True)
    username = forms.CharField(max_length=80, disabled=True)

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')


class DiagnosisForm(forms.ModelForm):
    class Meta:
        model = Diagnosis

        fields = (
            'symptoms',
        )

        labels = {
            'symptoms': 'Symptoms & Diagnosis',
        }

        widgets = {
            'symptoms': Textarea(attrs={'cols': 80, 'rows': 10}),
        }

welltory/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse, request, JsonResponse, Http404
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from django.views import generic
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required
from django.conf import settings
import os
import http.client
import urllib.parse
import json
from .models import (BioMarker,
                    Parameter,
                    Reading,
                    Disease,
                    Recommendation,
                    Practitioner,
                    Patient,
                    Diagnosis,
                    DiagnosisDoc
                    )
from .forms import (UserRegisterForm,
                    UserUpdateForm,
                    PractitionerUpdateForm,
                    PatientForm,
                    ProfileGrayedForm,
                    DiagnosisForm)
from .serializers import (BioMarkerSerializer,
                          ParameterSerializer,
                          ReadingSerializer,
                          DiseaseSerializer,
                          RecommendationSerializer)
from .utilities import ReadContents


# Create your views here.
class UserRegisterView(generic.CreateView):
    template_name = 'clinic/register.html'
    form_class = UserRegisterForm
    context_object_name = 'register'

    def signup(self):
        if self.request.method == 'POST':
            form = UserRegisterForm(self.request.POST)
            if form.is_valid():
                form.save()
                username = form.cleaned_data.get('username')
                raw_password = form.cleaned_data.get('password1')
                user = authenticate(username=username, password=raw_password)
                login(self.request, user)
                return HttpResponseRedirect('index')
            else:
                form = UserRegisterForm
                return render(self.request, 'register', {'form': form})


@login_required
def updateuser(request):
    if request.method == 'POST':
        form = UserUpdateForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('../profile')
    else:
        form = UserUpdateForm(instance=request.user)
        return render(request, 'clinic/updateuser.html', {'form': form})


class BioMarkerList(APIView):
    def get(self, request):
        bio_markers = BioMarker.objects.all()
        serializer = BioMarkerSerializer(bio_markers, many=True)
        return Response(serializer.data)

    def post(self, request):
        serializer = BioMarkerSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class ParameterList(APIView):
    def get(self, request):
        parameters = Parameter.objects.all()
        serializer = ParameterSerializer(parameters, many=True)
        return Response(serializer.data)

    def post(self, request):
        serializer = ParameterSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class ReadingList(APIView):
    def get(self, request):
        readings = Reading.objects.all()
        serializer = ReadingSerializer(readings, many=True)
        return Response(serializer.data)

    def post(self, request):
        serializer = ReadingSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class DiseaseList(APIView):
    def get(self, request):
        diseases = Disease.objects.all()
        serializer = ParameterSerializer(diseases, many=True)
        return Response(serializer.data)

    def post(self, request):
        serializer = DiseaseSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class RecommendationList(APIView):
    def get(self, request):
        recommendations = Recommendation.objects.all()
        serializer = RecommendationSerializer(recommendations, many=True)
        return Response(serializer.data)

    def post(self, request):
        serializer = RecommendationSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


@login_required
def home(request):
    context = {}
    return render(request, 'clinic/home.html', context)


@login_required
def updatepractitioner(request):
    if request.method == 'POST':
        form = PractitionerUpdateForm(request.POST, request.FILES, instance=request.user.practitioner)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('../profile')
    else:
        form = PractitionerUpdateForm(instance=request.user.practitioner)
        return render(request, 'clinic/updatepractitioner.html', {'form': form})


class ProfileView(LoginRequiredMixin, generic.FormView):
    template_name = 'clinic/profile.html'
    form_class = ProfileGrayedForm
    context_object_name = 'profile'

    def profile(self):
        form = ProfileGrayedForm
        return render(self.request, 'profile', {'form': form})


class PatientListView(LoginRequiredMixin, generic.ListView):
    model = Patient
    template_name = 'clinic/patientlist.html'
    context_object_name = 'patientlist'
    paginate_by = 20

    def get_queryset(self):
        return Patient.objects.order_by('-date_created')


class PatientCreateView(LoginRequiredMixin, generic.CreateView):
    template_name = 'clinic/patient_form.html'
    form_class = PatientForm
    context_object_name = 'createpatient'

    def createpatient(self):
        if self.request.method == 'POST':
            form = super(PatientCreateView, self).get_form(PatientForm)
            form.fields['date_field'].widget.attrs.update({'class': 'datepicker'})

    def form_valid(self, form):
        form.instance.created_by = self.request.user.practitioner
        return super().form_valid(form)


class PatientDetailView(LoginRequiredMixin, generic.DetailView):
    model = Patient
    template_name = 'clinic/patient_detail.html'


class PatientUpdateView(LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView):
    model = Patient
    template_name = 'clinic/patient_form.html'
    form_class = PatientForm
    context_object_name = 'updatepatient'

    def updatepatient(self):
        if self.request.method == 'POST':
            form = super(PatientUpdateView, self).get_form(PatientForm)
            form.fields['date_field'].widget.attrs.update({'class': 'datepicker'})

    def form_valid(self, form):
        form.instance.created_by = self.request.user.practitioner
        return super().form_valid(form)

    def test_func(self):
        patient = self.get_object()
        if self.request.user.practitioner == patient.created_by:
            return True
        else:
            return False


class PatientDeleteView(LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView):
    model = Patient
    template_name = 'clinic/patient_confirm_delete.html'
    success_url = '../../patientlist'

    def test_func(self):
        patient = self.get_object()
        if self.request.user.practitioner == patient.created_by:
            return True
        else:
            return False


class DiagnosisListView(LoginRequiredMixin, generic.ListView):
    model = Diagnosis
    template_name = 'clinic/diagnosislist.html'
    context_object_name = 'diagnosislist'
    paginate_by = 20

    def get_queryset(self):
        self.patient = get_object_or_404(Patient, national_id=self.kwargs['national_id'])
        patient = self.patient.id
        return Diagnosis.objects.filter(patient=patient).order_by('-date_created')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['patient'] = self.patient
        return context


class DiagnosisDetailView(LoginRequiredMixin, generic.DetailView):
    model = Diagnosis
    template_name = 'clinic/diagnosis_detail.html'


@login_required
def diagnosiscreate(request, national_id):
    if request.method == 'POST':
        form = DiagnosisForm(request.POST)
        if form.is_valid():
            patient = Patient.objects.get(national_id=national_id)
            diagnosis_id = patient.national_id
            patientinstance = form.save(commit=False)
            patientinstance.patient = patient
            patientinstance.practitioner = request.user.practitioner
            patientinstance.save()
            return HttpResponseRedirect('../diagnosislist/' + str(diagnosis_id))
        else:
            print(form.errors)
    else:
        form = DiagnosisForm()
        return render(request, 'clinic/diagnosis_form.html', {'form': form})


@login_required
def diagnosisuploadprep(request, national_id):
    diagnosis = national_id
    print(diagnosis)
    return render(request, 'clinic/diagnosisuploadprep.html', {'output': diagnosis})


@login_required
def diagnosisupload(request):
    if request.method == 'POST':
        myfile = request.FILES.get('file')

welltory/templates/clinic/diagnosis_form.html
{% extends 'clinic/main.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<br/>
<div class="row">
    <div class="col-lg-4">
        <br><br><br>
        <div class="box-element">
            <img class="img-profile rounded-circle" src="{{ object.image.url }}">
            <br/>
        </div>
    </div>
    <div class="col-lg-8">
        <div align="right">
            <a href="{% url 'welltory:patientlist' %}"
               class="d-none d-sm-inline-block btn btn-sm btn-secondary shadow-sm">
                <i class="fas fa-arrow-right fa-sm text-white-50"></i>Back To Patient List</a>
        </div>
        <br>
        <div class="box-element">
            <h3>Log Diagnosis</h3>
            <form method="POST">
                {% csrf_token %}
                <br/>
                {{ form.symptoms|as_crispy_field }}

                <br/><br/>
                <button class="btn btn-primary btn-icon-split btn btn-primary col-12">
                                        <span class="icon text-white-50">
                                            <i class="fas fa-arrow-right"></i>
                                        </span>
                    <span class="text"> Save Diagnosis</span>
                </button>
            </form>
        </div>
    </div>
</div>

</div>
<br/>
{% endblock content %}

welltory/templates/clinic/main.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>Longevity</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/rating.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1"/>
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{%url 'welltory:home' %}">Longevity</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Welltory</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                       Manage Actions Here
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{% url 'welltory:profile' %}">View My Profile</a></li>
                        <li><a class="dropdown-item" href="{% url 'welltory:updateuser' %}">Edit My User Details</a></li>
                        <li><a class="dropdown-item" href="{% url 'welltory:updatepractitioner' %}">
                            Edit My Practitioner Details</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="{% url 'welltory:patientlist' %}">View All Patients</a></li>
                        <li><a class="dropdown-item" href="{% url 'welltory:createpatient' %}">Create Patient Record</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <!--<li><a class="dropdown-item" href="#">Something else here</a></li>-->
                    </ul>
                </li>
               <!-- <li class="nav-item">
                    <a class="nav-link disabled">Disabled</a>
                </li>-->
            </ul>
            <form class="d-flex">
                <input class="form-control me-2" type="search" placeholder="Search... (inactive)" aria-label="Search">
                <button class="btn btn-outline-warning" type="submit">Search</button>
            </form>
        </div>
        <div class="form-inline my-2 my-lg-0">
            . .<a href="{% url 'welltory:logout'%}" class="btn btn-warning">Logout</a>
        </div>
        {% endif %}
    </div>
</nav>
<div class="container">
    {% block content %}


    {% endblock content %}
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous">

</script>
<br/>
</body>
<!-- Footer -->
<footer class="page-footer font-small bg-dark">

    <!-- Footer Elements -->

    <!-- Copyright -->
    <div class="footer-copyright text-center py-3"><font color="white">
        <small>Developed by Nyasha N. Chikwanda</small>
    </font>
    </div>
    <!-- Copyright -->

</footer>
<!-- Footer -->
</html>

welltory/templates/clinic/patient_detail.html
{% extends 'clinic/main.html' %}
{% load static %}
{% block content %}
<br/>
<div class="row">
    <div class="col-lg-4">
        <br><br><br>
        <div class="box-element" align="center">
            <img class="img-profile rounded-circle" src="{{ object.image.url }}">
            <div align="right">
                <div>
                    <a href="{% url 'welltory:diagnosislist' object.national_id %}"
                       class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm col-12">
                        <i class="fas fa-arrow-right fa-sm text-white-50"></i>Patient Records</a>
                </div>
            </div>
        </div>
    </div>

    <div class="col-lg-8">
        <div align="right">
            <a href="{% url 'welltory:patientlist' %}"
               class="d-none d-sm-inline-block btn btn-sm btn-secondary shadow-sm">
                <i class="fas fa-arrow-right fa-sm text-white-50"></i>Back To Patient List</a>
        </div>
        <br>
        <div class="box-element">
            <h4>Patient Details</h4>
            <div class="form-group row">
                <div class="col-sm-2 mb-3 mb-sm-0">
                    <p><b>First Name: </b></p>
                </div>
                <div class="col-sm-4">
                    <p>{{ object.first_name }}</p>
                </div>
                <div class="col-sm-2 mb-3 mb-sm-0">
                    <p><b>Last Name: </b></p>
                </div>
                <div class="col-sm-4">
                    <p>{{ object.last_name }}</p>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-2 mb-3 mb-sm-0">
                    <p><b>Email: </b></p>
                </div>
                <div class="col-sm-4">
                    <p>{{ object.email }}</p>
                </div>
                <div class="col-sm-2 mb-3 mb-sm-0">

                </div>
                <div class="col-sm-4">

                </div>
            </div>
            <hr>
            <div class="form-group row">
                <div class="col-sm-2 mb-3 mb-sm-0">
                    <p><b>Date Of Birth: </b></p>
                </div>
                <div class="col-sm-4">
                    <p>{{ object.dateOfBirth }}</p>
                </div>
                <div class="col-sm-2 mb-3 mb-sm-0">
                    <p><b>Gender </b></p>
                </div>
                <div class="col-sm-4">
                    <p>{{ object.gender }}</p>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-2 mb-3 mb-sm-0">
                    <p><b>National ID: </b></p>
                </div>
                <div class="col-sm-4">
                    <p>{{ object.national_id }}</p>
                </div>
                <div class="col-sm-2 mb-3 mb-sm-0">
                    <p><b>Mobile: </b></p>
                </div>
                <div class="col-sm-4">
                    <p>{{ object.mobile }}</p>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-2 mb-3 mb-sm-0">
                    <p><b>Address 1: </b></p>
                </div>
                <div class="col-sm-4">
                    <p>{{ object.street1 }}</p>
                </div>
                <div class="col-sm-2 mb-3 mb-sm-0">
                    <p><b>Address 2: </b></p>
                </div>
                <div class="col-sm-4">
                    <p>{{ object.street2 }}</p>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-2 mb-3 mb-sm-0">
                    <p><b>City: </b></p>
                </div>
                <div class="col-sm-4">
                    <p>{{ object.city }}</p>
                </div>
                <div class="col-sm-2 mb-3 mb-sm-0">
                    <p><b>Country: </b></p>
                </div>
                <div class="col-sm-4">
                    <p>{{ object.country.name }}</p>
                </div>
                <br>
            </div>
            <br/>
            <div>
                <a href="{% url 'welltory:updatepatient' object.id%}"
                   class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm btn btn-warning col-12">
                    <i class="fas fa-arrow-right fa-sm text-white-50"></i> Update Patient Details</a>
            </div>
            <br/>
            <div>
                <a href="{% url 'welltory:deletepatient' object.id%}"
                   class="d-none d-sm-inline-block btn btn-sm btn-danger shadow-sm btn btn-primary col-12">
                    <i class="fas fa-arrow-right fa-sm text-white-50"></i> Delete Patient Details</a>
            </div>
        </div>
        <br/>
    </div>
</div>
</div>

</div>
<br/>
{% endblock content %}

welltory/templates/clinic/patientlist.html
{% extends 'clinic/main.html' %}
{% load static %}
{% block content %}
<br/>
<div class="row">
    <div class="col-lg-12">
        <div align="right">
            <a href="{% url 'welltory:home' %}"
               class="d-none d-sm-inline-block btn btn-sm btn-secondary shadow-sm">
                <i class="fas fa-arrow-right fa-sm text-white-50"></i>Back To Dashboard</a>
            <a href="{% url 'welltory:createpatient' %}"
               class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm">
                <i class="fas fa-arrow-right fa-sm text-white-50"></i> Create Patient</a>
        </div>
        <br/>
        <div class="box-element">
            <h4>Patient List</h4>
            <table>
                <tr>
                    <td width="100"></td>
                    <td width="300"><b>Patient Name</b></td>
                    <td width="300"><b>D.O.B</b></td>
                    <td width="300"><b>Gender</b></td>
                    <td width="300"><b>Action</b></td>
                </tr>
                {% for patient in patientlist %}
                <tr>
                    <td></td>
                    <td><p>{{ patient.first_name }} {{ patient.last_name }}</p></td>
                    <td><p>{{ patient.dateOfBirth }}</p></td>
                    <td><p>{{ patient.gender }}</p></td>
                    <td><p><a href="{% url 'welltory:patientdetails' patient.id %}"
                              class="d-none d-sm-inline-block btn btn-sm btn-success shadow-sm">
                        <i class="fas fa-arrow-right fa-sm text-white-50"></i> View</a>
                        <a href="{% url 'welltory:updatepatient' patient.id %}"
                           class="d-none d-sm-inline-block btn btn-sm btn-warning shadow-sm">
                            <i class="fas fa-info fa-sm text-white-50"></i> Update</a>
                        <a href="{% url 'welltory:deletepatient' patient.id %}"
                           class="d-none d-sm-inline-block btn btn-sm btn-danger shadow-sm">
                            <i class="fas fa-trash fa-sm text-white-50"></i> Delete</a></p></td>
                </tr>
                {% endfor %}

                <tr>
                    <td></td>
                    <td>
                        <div align="center">
                            <!--PAGINATION-->
                            {% if is_paginated %}

                            {% if page_obj.has_previous %}
                            <a class="btn btn-outline-info mb-4" href="?page=1"> << </a>
                            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">
                                < </a>
                            {% endif %}

                            {% for num in page_obj.paginator.page_range %}
                            {% if page_obj.number == num %}
                            <a class="btn btn-info mb-4" href="?page={{ num }}"> {{ num }} </a>
                            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                            <a class="btn btn-outline-info mb-4" href="?page={{ num }}"> {{ num }} </a>
                            {% endif %}
                            {% endfor %}

                            {% if page_obj.has_next %}
                            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">
                                > </a>
                            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">
                                >> </a>
                            {% endif %}

                            {% endif %}
                        </div>
                    </td>
                    <td></td>
                    <td></td>
                </tr>
            </table>
        </div>
    </div>
</div>
</div>

</div>
<br/>
{% endblock content %}